receive:
  kafka:
    server: logs.liexiong.net:29094
    topic: public
    group_id: test10
    size: 1000
    timeout: 1000
sender:
  clickhouse:
    server: 10.10.1.5
    username: default
    password: Lxasd123!@#
# 